@host = localhost
@port = 8000

### Pregunta sobre recorrido fotografía
POST http://{{host}}:{{port}}/query
Content-Type: application/json

{
    "query": "Quiero realizar un recorrido de fotografía, pero no veo nada parecido"
}

### Guardar pregunta
POST http://{{host}}:{{port}}/save
Content-Type: application/json

{
    "query": "Quiero realizar un recorrido de fotografía, pero no veo nada parecido",
    "template": "template1",
    "feedback": 5
}
